//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZzukBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AntiQuery {
            get {
                object obj = ResourceManager.GetObject("AntiQuery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] appsettings {
            get {
                object obj = ResourceManager.GetObject("appsettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] beep {
            get {
                object obj = ResourceManager.GetObject("beep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cleverbot {
            get {
                object obj = ResourceManager.GetObject("cleverbot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fasm_NET {
            get {
                object obj = ResourceManager.GetObject("Fasm_NET", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FastCall {
            get {
                object obj = ResourceManager.GetObject("FastCall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Loader {
            get {
                object obj = ResourceManager.GetObject("Loader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wow.exe
        ///ntdll.dll
        ///kernel32.dll
        ///kernelbase.dll
        ///advapi32.dll
        ///msvcrt.dll
        ///sechost.dll
        ///rpcrt4.dll
        ///sspicli.dll
        ///cryptbase.dll
        ///comctl32.dll
        ///gdi32.dll
        ///user32.dll
        ///lpk.dll
        ///usp10.dll
        ///shell32.dll
        ///shlwapi.dll
        ///wsock32.dll
        ///ws2_32.dll
        ///nsi.dll
        ///opengl32.dll
        ///glu32.dll
        ///ddraw.dll
        ///dciman32.dll
        ///setupapi.dll
        ///cfgmgr32.dll
        ///oleaut32.dll
        ///ole32.dll
        ///devobj.dll
        ///dwmapi.dll
        ///imm32.dll
        ///msctf.dll
        ///divxdecoder.dll
        ///winmm.dll
        ///fmod.dll
        ///msacm32.dll
        ///wininet.dll
        ///api-ms-win-downlevel-user32-l1-1-0.dll
        ///api-ms-win-do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModulesOfWoW {
            get {
                return ResourceManager.GetString("ModulesOfWoW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PathFinder {
            get {
                object obj = ResourceManager.GetObject("PathFinder", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
